// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: HealthCheck.proto

package org.myddd.vertx.grpc;

public final class HealthCheckProto {
  private HealthCheckProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_org_myddd_vertx_grpc_NodeInfo_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_org_myddd_vertx_grpc_NodeInfo_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    String[] descriptorData = {
      "\n\021HealthCheck.proto\022\024org.myddd.vertx.grp" +
      "c\032\033google/protobuf/empty.proto\032\036google/p" +
      "rotobuf/wrappers.proto\"&\n\010NodeInfo\022\014\n\004ho" +
      "st\030\001 \001(\t\022\014\n\004port\030\002 \001(\0052\222\001\n\013HealthCheck\022=" +
      "\n\005hello\022\026.google.protobuf.Empty\032\032.google" +
      ".protobuf.BoolValue\"\000\022D\n\010nodeInfo\022\026.goog" +
      "le.protobuf.Empty\032\036.org.myddd.vertx.grpc" +
      ".NodeInfo\"\000B*\n\024org.myddd.vertx.grpcB\020Hea" +
      "lthCheckProtoP\001b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.google.protobuf.EmptyProto.getDescriptor(),
          com.google.protobuf.WrappersProto.getDescriptor(),
        });
    internal_static_org_myddd_vertx_grpc_NodeInfo_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_org_myddd_vertx_grpc_NodeInfo_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_org_myddd_vertx_grpc_NodeInfo_descriptor,
        new String[] { "Host", "Port", });
    com.google.protobuf.EmptyProto.getDescriptor();
    com.google.protobuf.WrappersProto.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
