// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: HealthCheck.proto

package org.myddd.vertx.grpc;

public final class HealthCheckProto {
  private HealthCheckProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\021HealthCheck.proto\022\024org.myddd.vertx.grp" +
      "c\032\033google/protobuf/empty.proto\032\036google/p" +
      "rotobuf/wrappers.proto2L\n\013HealthCheck\022=\n" +
      "\005hello\022\026.google.protobuf.Empty\032\032.google." +
      "protobuf.BoolValue\"\000B*\n\024org.myddd.vertx." +
      "grpcB\020HealthCheckProtoP\001b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.google.protobuf.EmptyProto.getDescriptor(),
          com.google.protobuf.WrappersProto.getDescriptor(),
        });
    com.google.protobuf.EmptyProto.getDescriptor();
    com.google.protobuf.WrappersProto.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
