// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: HealthCheck.proto

package org.myddd.vertx.grpc;

public interface NodeInfoOrBuilder extends
    // @@protoc_insertion_point(interface_extends:org.myddd.vertx.grpc.NodeInfo)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string host = 1;</code>
   * @return The host.
   */
  String getHost();
  /**
   * <code>string host = 1;</code>
   * @return The bytes for host.
   */
  com.google.protobuf.ByteString
      getHostBytes();

  /**
   * <code>int32 port = 2;</code>
   * @return The port.
   */
  int getPort();
}
